name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    env:
      PUBLIC_VAR: public_value
      ANOTHER_PUBLIC_VAR: another_public_value
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '16'
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          secrets: |
            SECRET_KEY=${{ secrets.SECRET_KEY }}
            API_ENDPOINT=${{ secrets.API_ENDPOINT }}
          vars: |
            FOO=bar
            EXAMPLE_VAR=example_value
